FROM blockstream/verde@sha256:9171360dae48d3fba7c0f36ab5eb45e2529d178a603e89197cb08fb123ca619e as builder

ARG SDK_CONFIG=configs/sdkconfig_qemu_psram.defaults

WORKDIR /jade

COPY . .
RUN cp ${SDK_CONFIG} sdkconfig.defaults
RUN . /root/esp/esp-idf/export.sh && idf.py all
RUN . /root/esp/esp-idf/export.sh && pip install zopfli && ./tools/fwprep.py build/jade.bin build

ENV PATH=$PATH:/jade/main/qemu
RUN make-flash-img.sh
RUN . /root/esp/esp-idf/export.sh && cp $(which qemu-system-xtensa) /qemu-system-xtensa && \
    QEMU_DIR=$(dirname $(dirname $(which qemu-system-xtensa))) && \
    cp -r $QEMU_DIR/share /qemu-share

FROM debian:bookworm-slim@sha256:12c396bd585df7ec21d5679bb6a83d4878bc4415ce926c9e5ea6426d23c60bdc

RUN apt-get update -yqq && apt-get install -yqq libpixman-1-dev libglib2.0-dev libslirp-dev libncurses-dev libsdl2-2.0-0 procps

COPY --from=builder /flash_image.bin /flash_image.bin
COPY --from=builder /qemu_efuse.bin /qemu_efuse.bin

COPY --from=builder /jade/main/qemu/ /jade/main/qemu/
COPY --from=builder /qemu-system-xtensa /usr/local/bin/qemu-system-xtensa
COPY --from=builder /qemu-share /usr/local/share

ENV PATH=$PATH:/jade/main/qemu

CMD [ "/jade/main/qemu/qemu_run_standalone.sh" ]
